#if defined(DLE_KERNEL) && defined(DLE_USER)
#error "Cannot define both DLE_KERNEL and DLE_USER"
#elif !defined(DLE_KERNEL) && !defined(DLE_USER)
#error "Either DLE_KERNEL or DLE_USER must be defined"
#endif

#ifdef DLE_KERNEL
#include <ntddk.h>
#endif
#ifdef DLE_USER
#include <Windows.h>
#endif

#define IOCTL_READ_PARTITION CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PARTITION_INFO_GET CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PARTITION_SECTOR_INFO_GET CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PHYSICAL_MEMORY_READ_ANY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PARTITION_READ CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _READ_PARTITION_INPUT {
	LARGE_INTEGER Offset;
	ULONG Length;
} READ_PARTITION_INPUT, * PREAD_PARTITION_INPUT;
typedef struct _PARTITION_INFO_GET_IN {
	ULONG diskNumber;
	ULONG partitionNumber;
} PARTITION_INFO_GET_IN, * PPARTITION_INFO_GET_IN;
typedef struct _PARTITION_INFO_GET_OUT {
	ULONG PartitionStyle;
	LARGE_INTEGER StartingOffset;
	LARGE_INTEGER PartitionLength;
	ULONG PartitionNumber;
	BOOLEAN RewritePartition;

	UCHAR MbrPartitionType;
	BOOLEAN MbrBootIndicator;
	BOOLEAN MbrRecognizedPartition;
	ULONG MbrHiddenSectors;

	GUID GptPartitionType;
	GUID GptPartitionId;
	ULONGLONG GptAttributes;
	WCHAR GptName[36];
} PARTITION_INFO_GET_OUT, * PPARTITION_INFO_GET_OUT;
typedef struct _PARTITION_SECTOR_INFO_GET_IN {
	ULONG diskNumber;
	ULONG partitionNumber;
} PARTITION_SECTOR_INFO_GET_IN, * PPARTITION_SECTOR_INFO_GET_IN;
typedef struct _PARTITION_SECTOR_INFO_GET_OUT {
	ULONG BytesPerSector;
	ULONGLONG TotalSectors;
	ULONGLONG TotalBytes;
	LARGE_INTEGER Cylinders;
	MEDIA_TYPE MediaType;
	ULONG SectorsPerTrack;
	ULONG TracksPerCylinder;
	WCHAR VolumeLabel[32];
} PARTITION_SECTOR_INFO_GET_OUT, * PPARTITION_SECTOR_INFO_GET_OUT;
typedef struct _PHYSICAL_MEMORY_READ_ANY_IN {
	UINT64 physAddr;
	UINT32 size;
} PHYSICAL_MEMORY_READ_ANY_IN, * PPHYSICAL_MEMORY_READ_ANY_IN;
typedef struct _PARTITINON_READ_IN {
	DWORD partitionNum;
	DWORD diskNum;
	LARGE_INTEGER offset;
	ULONG length;
} PARTITION_READ_IN, * PPARTITION_READ_IN;